### ISSUE TITLE
Kernel Panic

### ISSUE THREAD

**Issue by tay10r** [Ross-Software/BlueSkyOS#1]
I tried running this operating system on QEMU.

It complained about not being able to execute `/sbin/v86d`.

Here's an image:

![screenshot from 2018-01-31 17-50-38](https://user-images.githubusercontent.com/4486381/35651876-4347cc54-06af-11e8-91c4-63feb8a0a6c1.png)

**Comment by SpaceboyRoss01** [comment]
The actual error was that the rootfs couldn’t mount, did you make sure the image is not a hdd but a cdrom.

**Comment by tay10r** [comment]
Thanks!
